// ./src/actions/actionTypes.js
export const GET_ASSET_DATA_SUCCESS: string = 'GET_ASSET_DATA_SUCCESS';
export const GET_ALLOCATION_DATA_SUCCESS: string = 'GET_ALLOCATION_DATA_SUCCESS';
export const CLEAR_ADJUST_CASH_DATA: string = 'CLEAR_ADJUST_CASH_DATA';
export const SHOW_ADJUST_CASH_MODAL: string = 'SHOW_ADJUST_CASH_MODAL';
export const HIDE_ADJUST_CASH_MODAL: string = 'HIDE_ADJUST_CASH_MODAL';
export default {
    GET_ASSET_DATA_SUCCESS,
    GET_ALLOCATION_DATA_SUCCESS,
    CLEAR_ADJUST_CASH_DATA,
    SHOW_ADJUST_CASH_MODAL,
    HIDE_ADJUST_CASH_MODAL
};
